# 這個區塊定義了一個名為 'dbt_demo' 的連線設定
# 它是你的 dbt 專案與 BigQuery 資料庫之間的橋樑。
dbt_demo:

  # 指定預設的目標環境。當你執行 dbt 指令時，它會使用 'dev' 這個設定。
  target: dev

  # 定義所有可用的目標環境。這裡只有一個 'dev' 環境。
  outputs:

    # 'dev' 環境的詳細設定。
    dev:
      # 指定資料庫類型為 BigQuery。
      type: bigquery

      # 指定認證方式為 'service-account'。這表示 dbt 會使用一個服務帳號的金鑰來進行身份驗證。
      method: service-account

      # 指定你的 Google Cloud 專案 ID。dbt 會在這個專案中執行所有操作。
      project: ubike-471005

      # 指定 dbt 最終的資料模型 (models) 會被寫入哪一個 BigQuery 資料集。
      # 這裡我們將它指向 'ubike_471005_data_warehouse'。
      dataset: ubike_471005_data_warehouse

      # 設定 dbt 可以同時執行的執行緒數量，通常用於提高效能。
      threads: 1

      # 指定服務帳號金鑰檔案的本地路徑。dbt 會讀取這個檔案來進行認證。
      keyfile: /home/pohengchou/ubike_cosmos/include/keys/service_account.json

      # 設定查詢逾時時間，單位為秒。
      timeout_seconds: 300

      # 指定 BigQuery 資料集所在的地理位置。
      location: asia-east1